name: env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2.0.0
  - scipy
  - matplotlib
  - casadi=3.6.*
  - onnx
  - ipython
  - jupyter
  - sphinx
  - nbsphinx
  - pygments
  - docutils
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - sphinx-book-theme
  - graphviz
  - myst-parser
  - packaging
  - asyncua

  # install with:
  # conda env create --prefix ./.venv -f .conda.yml  
